package net.prefixaut.deadalus.css;

public interface MediaFeatureType<T extends Comparable<T>> {
	
	public boolean check(T value);
	
//	ASPECT_RATIO,
//	COLOR,
//	COLOR_INDEX,
//	DEVICE_ASPECT_RATIO,
//	DEVICE_HEIGHT,
//	DEVICE_WIDTH,
//	GRID,
//	HEIGHT,
//	MAX_ASPECT_RATIO,
//	MAX_COLOR,
//	MAX_COLOR_INDEX,
//	MAX_DEVICE_ASPECT_RATIO,
//	MAX_DEVICE_HEIGHT,
//	MAX_DEVICE_WIDTH,
//	MAX_HEIGHT,
//	MAX_MNOCHROME,
//	MAX_RESOLUTION,
//	MAX_WIDTH,
//	MIN_ASPECT_RATIO,
//	MIN_COLOR,
//	MIN_COLOR_INDEX,
//	MIN_DEVICE_ASPECT_RATIO,
//	MIN_DEVICE_WIDTH,
//	MIN_DEVICE_HEIGHT,
//	MIN_HEIGHT,
//	MIN_MONOCHROME,
//	MIN_RESOLUTION,
//	MIN_WIDTH,
//	MONOCHROME,
//	ORIENTATION,
//	OVERFLOW_BLOCK,
//	OVERFLOW_INLINE,
//	RESOLUTION,
//	SCAN,
//	UPDATE_FREQUENCY,
//	WIDTH;
}